"""Self-check: verify every hard-coded number in the paper prose against the
current pipeline outputs.

The paper's *tables* are auto-generated by 17_make_tables.py, so they cannot
drift from the code. The risk is the numbers typed by hand into the prose of
paper/paper_word.tex (and the Word draft): coefficients, p-values, CIs, ranges.
This script re-reads the fresh output/*.csv and data/*.csv and checks each such
claim. Run it after re-running the pipeline (or after any regression change):

    python code/verify_numbers.py

Exit code 0 => every prose number matches. Exit code 1 => at least one drifted;
the offending rows are printed with the claimed vs. actual value.

Each check stores the claim as it appears in the paper (already rounded) and an
extractor that pulls the full-precision value from a CSV. A claim passes when the
actual value, rounded to the claim's decimal places, equals the claim (with a
small absolute fallback tolerance for the last digit).
"""
from pathlib import Path
import sys
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT, DATA = ROOT / "output", ROOT / "data"

_cache = {}
def csv(name, folder=OUT):
    key = (folder, name)
    if key not in _cache:
        _cache[key] = pd.read_csv(folder / name)
    return _cache[key]

def cell(name, col, folder=OUT, **eq):
    """Single value from `name`.csv at row matching all eq filters, column `col`.
    String filters match by substring (case-insensitive); numeric by equality."""
    d = csv(name, folder)
    m = pd.Series(True, index=d.index)
    for k, v in eq.items():
        if isinstance(v, str):
            m &= d[k].astype(str).str.contains(v, case=False, regex=False)
        else:
            m &= (d[k] == v)
    sub = d.loc[m, col]
    if len(sub) != 1:
        raise LookupError(f"{name}.csv[{col}] with {eq} -> {len(sub)} rows (want 1)")
    return float(sub.iloc[0])

# ---------------------------------------------------------------------------
# Each check: (section, description, claimed_value, decimals, actual_fn)
#   claimed_value  = the number as written in the paper prose
#   decimals       = decimal places the prose rounds to (for the match test)
#   actual_fn      = () -> full-precision value from the pipeline
# ---------------------------------------------------------------------------
CHECKS = [
    # -- data / intensity --
    ("Data", "MMI min (northern desert)", 2.9, 1,
        lambda: csv("shakemap_by_region.csv", DATA)["mean_mmi"].min()),
    ("Data", "MMI max (Maule/O'Higgins)", 6.7, 1,
        lambda: csv("shakemap_by_region.csv", DATA)["mean_mmi"].max()),

    # -- main investment DiD (Table 1 / prose) --
    ("Main", "investment Post x MMI, no trend", 0.52, 2,
        lambda: cell("earthquake_did_main.csv", "beta", sample="MAIN", outcome="investment", treat="post_mmi", trends="none")),
    ("Main", "investment Post x MMI, +region linear trend", 0.17, 2,
        lambda: cell("earthquake_did_main.csv", "beta", sample="MAIN", outcome="investment", treat="post_mmi", trends="linear")),

    # -- event study (pre-projected detrend) --
    ("Event study", "investment 2014 (pre-projected)", 0.58, 2,
        lambda: cell("earthquake_event_study_pretrend.csv", "beta", outcome="invest", year=2014)),
    ("Event study", "investment 2015 (pre-projected)", 0.60, 2,
        lambda: cell("earthquake_event_study_pretrend.csv", "beta", outcome="invest", year=2015)),
    ("Event study", "investment 2014, no detrending", 0.71, 2,
        lambda: cell("earthquake_event_study.csv", "beta", outcome="invest", year=2014)),
    ("Event study", "investment 2014, full-sample detrend", 0.40, 2,
        lambda: cell("earthquake_event_study_detrended.csv", "beta", outcome="invest", year=2014)),

    # -- wild cluster bootstrap --
    ("Bootstrap", "2014 investment pulse p-value (WCB)", 0.027, 3,
        lambda: cell("wild_bootstrap.csv", "p_wcb", estimate="2014 investment pulse")),

    # -- robustness of the 2014 pulse --
    ("Robustness", "2014 pulse low end (all manufacturing)", 0.56, 2,
        lambda: cell("earthquake_robustness_pulse.csv", "beta_2014", variant="all manufacturing")),
    ("Robustness", "2014 pulse high end (tight 2007-2017)", 0.88, 2,
        lambda: cell("earthquake_robustness_pulse.csv", "beta_2014", variant="tight window")),
    ("Robustness", "2014 pulse, binary MMI>=6", 1.87, 2,
        lambda: cell("earthquake_robustness_pulse.csv", "beta_2014", variant="binary")),

    # -- incidence / wage bill --
    ("Incidence", "wage bill (REMPAG) Post x MMI", 0.14, 2,
        lambda: cell("incidence_did.csv", "beta", outcome="Wage bill")),
    ("Incidence", "wage bill p-value", 0.014, 3,
        lambda: cell("incidence_did.csv", "p", outcome="Wage bill")),

    # -- wage decomposition / mechanism --
    ("Wages", "unskilled wage avg post", 0.26, 2,
        lambda: cell("wage_mechanism_checks.csv", "avg_beta", check="C2 unskilled wage baseline")),
    ("Wages", "unskilled wage peak 2014", 0.52, 2,
        lambda: cell("wage_mechanism_checks.csv", "y2014_beta", check="C2 unskilled wage baseline")),
    ("Wages", "skill-premium effect avg", -0.19, 2,
        lambda: cell("wage_mechanism_checks.csv", "avg_beta", check="skill-premium effect")),

    # -- asset decomposition 2014 --
    ("Assets", "structures 2014", 0.82, 2,
        lambda: cell("asset_decomposition_pulse.csv", "beta", asset="Structures", year=2014)),
    ("Assets", "machinery 2014", 0.49, 2,
        lambda: cell("asset_decomposition_pulse.csv", "beta", asset="Machinery", year=2014)),
    ("Assets", "equipment 2014", 0.52, 2,
        lambda: cell("asset_decomposition_pulse.csv", "beta", asset="Equipment", year=2014)),
    ("Assets", "equipment avg-post vs pre-trend", 0.34, 2,
        lambda: cell("wild_bootstrap.csv", "beta", estimate="equipment")),

    # -- construction-sector placebo (CASEN) --
    ("Construction", "construction employment", 0.02, 2,
        lambda: cell("casen_construction_did.csv", "beta", outcome="construction employment")),
    ("Construction", "construction employment p", 0.36, 2,
        lambda: cell("casen_construction_did.csv", "p", outcome="construction employment")),
    ("Construction", "construction wage", -0.04, 2,
        lambda: cell("casen_construction_did.csv", "beta", outcome="construction wage")),
    ("Construction", "construction wage p", 0.09, 2,
        lambda: cell("casen_construction_did.csv", "p", outcome="construction wage")),

    # -- CASEN migration --
    ("CASEN", "unskilled population Post x MMI", 0.002, 3,
        lambda: cell("casen_migration_did.csv", "beta", outcome="Unskilled population")),
    ("CASEN", "total population Post x MMI", -0.009, 3,
        lambda: cell("casen_migration_did.csv", "beta", outcome="Total population")),
    ("CASEN", "pre-trend joint F", 2.60, 2,
        lambda: cell("casen_honestdid.csv", "param", kind="pretrend_F")),
    ("CASEN", "pre-trend joint F p-value", 0.12, 2,
        lambda: cell("casen_honestdid.csv", "p", kind="pretrend_F")),
    ("CASEN", "HonestDiD RM(1) lower bound", -0.07, 2,
        lambda: cell("casen_honestdid.csv", "lb", kind="RM", param=1.0)),
    ("CASEN", "HonestDiD RM(1) upper bound", 0.12, 2,
        lambda: cell("casen_honestdid.csv", "ub", kind="RM", param=1.0)),

    # -- main HonestDiD (SD(0) robust CIs) --
    ("HonestDiD", "investment SD(0) lower", 0.28, 2,
        lambda: cell("honestdid_results.csv", "lb", outcome="Investment", restriction="SD", param=0.0)),
    ("HonestDiD", "investment SD(0) upper", 0.75, 2,
        lambda: cell("honestdid_results.csv", "ub", outcome="Investment", restriction="SD", param=0.0)),
    ("HonestDiD", "unskilled wage SD(0) lower", 0.19, 2,
        lambda: cell("honestdid_results.csv", "lb", outcome="Unskilled wage", restriction="SD", param=0.0)),
    ("HonestDiD", "unskilled wage SD(0) upper", 0.80, 2,
        lambda: cell("honestdid_results.csv", "ub", outcome="Unskilled wage", restriction="SD", param=0.0)),
    ("HonestDiD", "investment breakdown Mbar", 0.5, 1,
        lambda: cell("honestdid_results.csv", "param", outcome="Investment", restriction="breakdown_Mbar")),
    ("HonestDiD", "unskilled wage breakdown Mbar", 0.5, 1,
        lambda: cell("honestdid_results.csv", "param", outcome="Unskilled wage", restriction="breakdown_Mbar")),

    # -- spillover (SLX) --
    ("Spillover", "investment neighbor coef", 0.51, 2,
        lambda: cell("spillover_test.csv", "theta_nbr", outcome="Investment")),
    ("Spillover", "investment neighbor p-value", 0.64, 2,
        lambda: cell("spillover_test.csv", "p_nbr", outcome="Investment")),
    ("Spillover", "output own coef, own-only", 0.11, 2,
        lambda: cell("spillover_test.csv", "beta_own_only", outcome="Gross output")),
    ("Spillover", "output own coef, augmented", 1.06, 2,
        lambda: cell("spillover_test.csv", "beta_own_aug", outcome="Gross output")),
    ("Spillover", "output neighbor coef", -0.97, 2,
        lambda: cell("spillover_test.csv", "theta_nbr", outcome="Gross output")),
]


def match(claimed, actual, decimals):
    """Pass if actual rounds to the claim, or is within half a ULP of the last
    printed digit (covers banker's-rounding edge cases)."""
    if actual is None or (isinstance(actual, float) and np.isnan(actual)):
        return False
    tol = 0.5 * 10 ** (-decimals) + 1e-9
    return (round(actual, decimals) == round(claimed, decimals)) or (abs(actual - claimed) <= tol)


def main():
    rows, n_fail = [], 0
    for section, desc, claimed, dec, fn in CHECKS:
        try:
            actual = fn()
            ok = match(claimed, actual, dec)
            act_s = f"{actual:.{max(dec,3)}f}"
        except Exception as e:                      # missing CSV / row -> hard fail
            ok, act_s = False, f"ERR: {e}"
        n_fail += not ok
        rows.append((section, desc, f"{claimed:+.{dec}f}", act_s, "ok" if ok else "MISMATCH"))

    w0 = max(len(r[0]) for r in rows)
    w1 = max(len(r[1]) for r in rows)
    w2 = max(len(r[2]) for r in rows)
    w3 = max(len(r[3]) for r in rows)
    print(f"{'SECTION':<{w0}}  {'CLAIM':<{w1}}  {'PAPER':>{w2}}  {'PIPELINE':>{w3}}  STATUS")
    print("-" * (w0 + w1 + w2 + w3 + 16))
    for sec, desc, cl, ac, st in rows:
        flag = "" if st == "ok" else "  <<<<<<"
        print(f"{sec:<{w0}}  {desc:<{w1}}  {cl:>{w2}}  {ac:>{w3}}  {st}{flag}")

    total = len(rows)
    print("-" * (w0 + w1 + w2 + w3 + 16))
    if n_fail == 0:
        print(f"ALL {total} prose numbers match the current pipeline outputs.")
    else:
        print(f"{n_fail} of {total} checks MISMATCH -- prose is out of sync with the pipeline.")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
